format = """
$directory\
[](fg:light_blue bg:dark_blue)\
$git_branch\
$git_status\
[](fg:dark_blue)\
$fill\
[](fg:darker_blue)\
$nodejs\
$rust\
$golang\
$php\
[](fg:darkest_blue bg:darker_blue)\
$time\
[](fg:light_blue bg:darkest_blue)\
$os\
[](fg:light_blue)\
\n$character"""

add_newline = false
scan_timeout = 30
command_timeout = 500

# カラーパレット定義
palette = "nord"

[palettes.nord]
dark_bg = "#2E3440"
light_blue = "#88C0D0"
blue = "#769ff0"
dark_blue = "#394260"
darker_blue = "#212736"
darkest_blue = "#1d2230"
light_gray = "#a0a9cb"

[fill]
symbol = ' '

[os]
format = "[$symbol]($style)"
style = "fg:dark_bg bg:light_blue bold"
disabled = false

[os.symbols]
Macos = "  " # nf-fa-apple
Ubuntu = "  " # nf-linux-ubuntu
Debian = "  " # nf-linux-debian

[directory]
style = "fg:dark_bg bg:light_blue bold"
format = "[ $path ]($style)"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true


[git_branch]
symbol = ""
style = "bg:dark_blue"
format = '[[ $symbol $branch ](fg:blue bg:dark_blue)]($style)'

[git_status]
style = "bg:dark_blue"
format = '[[($all_status$ahead_behind )](fg:blue bg:dark_blue)]($style)'

[nodejs]
symbol = ""
style = "bg:darker_blue"
format = '[[ $symbol ($version) ](fg:blue bg:darker_blue)]($style)'
version_format = 'v${raw}'

[rust]
symbol = ""
style = "bg:darker_blue"
format = '[[ $symbol ($version) ](fg:blue bg:darker_blue)]($style)'
version_format = 'v${raw}'

[golang]
symbol = ""
style = "bg:darker_blue"
format = '[[ $symbol ($version) ](fg:blue bg:darker_blue)]($style)'
version_format = 'v${raw}'

[php]
symbol = ""
style = "bg:darker_blue"
format = '[[ $symbol ($version) ](fg:blue bg:darker_blue)]($style)'
version_format = 'v${raw}'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:darkest_blue"
format = '[[  $time ](fg:light_gray bg:darkest_blue)]($style)'
